export const GET_CLOUD_TAGS="GET_CLOUD_TAGS";
export const GET_CLOUD_TAGS_SUCCESS="GET_CLOUD_TAGS_SUCCESS";
export const GET_CLOUD_TAGS_FAILURE="GET_CLOUD_TAGS_FAILURE";

export const GET_CLOUD_TAG="GET_CLOUD_TAG";
export const GET_CLOUD_TAG_SUCCESS="GET_CLOUD_TAG_SUCCESS";
export const GET_CLOUD_TAG_FAILURE="GET_CLOUD_TAG_FAILURE";